@startuml

' Диаграмма активностей
' Отвечает на вопрос: какой алгоритм, последовательность действий препдоплагается

title "Алгоритм проведения валидации"

start
    :Проверить что указан ИНН и КПП;
    :Проверить что указан ОГРН;

    if (это юридическое лицо) then (да)
        :Проверить юридичкое лицо;
    endif

    :Вывести информацию пользователю;
end

@enduml