@startuml
start

:Получение заявки на оплату;
if (Необходимо провести дополнительные проверки?) then (да)
  :Проведение дополнительных проверок;
else (нет)
endif

:Проверка заявки на соответствие правилам компании;
if (Заявка отклонена?) then (да)
  :Отправка уведомления об отклонении заявки;
else (нет)
  :Направление заявки на согласование;
endif

if (Требуется дополнительное согласование?) then (да)
  :Проведение дополнительного согласования;
else (нет)
  :Отправка заявки на оплату в бухгалтерию;
endif

:Проведение оплаты;
if (Оплата не прошла?) then (да)
  :Отправка уведомления об ошибке оплаты;
else (нет)
  :Отправка уведомления о проведении оплаты;
endif

stop
@enduml