@startuml
' Диаграмма состояний
' Отвечает на вопрос: в каких состояних (статусах) может находится тот или иной объект
' Основные составлющие: Состояния, Взаимосвязи

title "Статусную модель анкеты контагента"

[*] --> Черновик : Пользователь создает заявку
Черновик --> Согласуется : Пользователь отправил заявку
Согласуется --> Валидируется : Закупщик валидирует корректность заявки
Согласуется --> Черновик : Закупщик не согласова добавление заявки, отправил на доработку

Валидируется --> Согласована : Проверка выполнена
Согласована --> Выполнена : Данные анкеты добавлены в справочник
Выполнена --> [*]

'Отмена
Черновик --> Отмена
Согласуется --> Отмена
Валидируется --> Отмена
Отмена --> [*]

@enduml